"""add datos

Revision ID: 7b1971447980
Revises: d8af265701ef
Create Date: 2025-05-02 00:11:48.928847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1971447980'
down_revision: Union[str, None] = 'd8af265701ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'datos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datos', type_='foreignkey')
    op.drop_column('datos', 'user_id')
    # ### end Alembic commands ###
